import clientPromise from "@/lib/db";

/**
 * Seeded recipes data with proper ingredient amounts
 * These are the first 15 recipes that should be seeded into the database
 */
const SEEDED_RECIPES = [
  {
    title: "Classic Spaghetti Carbonara",
    cuisine: "Italian",
    skill: "intermediate",
    dietary: ["gluten-free alternative available"],
    cookingTime: 20,
    ingredients: [
      { name: "spaghetti", amount: 1, unit: "pound" },
      { name: "eggs", amount: 4, unit: "" },
      { name: "Pecorino Romano cheese", amount: 0.5, unit: "cup" },
      { name: "pancetta", amount: 0.5, unit: "pound" },
      { name: "black pepper", amount: 0.5, unit: "teaspoon" },
      { name: "salt", amount: 1, unit: "teaspoon" },
    ],
    steps: [
      "Bring a large pot of salted water to a boil.",
      "Cut pancetta into small pieces and cook in a large skillet over medium-high heat until crispy.",
      "Cook spaghetti according to package directions until al dente.",
      "In a bowl, whisk together eggs, grated Pecorino Romano cheese, and black pepper.",
      "Reserve 1 cup of pasta cooking water before draining.",
      "Add the drained pasta to the pancetta skillet and remove from heat.",
      "Pour the egg mixture over the pasta and toss constantly, adding pasta water a little at a time to create a creamy sauce.",
      "Serve immediately with extra cheese and black pepper.",
    ],
    equipment: ["large pot", "skillet", "tongs", "whisk", "bowl"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Cilantro Lime Rice",
    cuisine: "Mexican",
    skill: "beginner",
    dietary: ["vegan", "gluten-free"],
    cookingTime: 25,
    ingredients: [
      { name: "white rice", amount: 2, unit: "cups" },
      { name: "cilantro", amount: 0.33333, unit: "cup" },
      { name: "lime juice", amount: 0.25, unit: "cup" },
      { name: "olive oil", amount: 2, unit: "tablespoons" },
      { name: "garlic cloves", amount: 2, unit: "" },
      { name: "vegetable broth", amount: 4, unit: "cups" },
      { name: "salt", amount: 0.5, unit: "teaspoon" },
    ],
    steps: [
      "Heat olive oil in a large pot over medium-high heat.",
      "Add minced garlic and cook for 1 minute until fragrant.",
      "Add rice and toast for 2-3 minutes, stirring constantly.",
      "Pour in vegetable broth and bring to a boil.",
      "Reduce heat to low, cover, and simmer for 15-20 minutes until rice is tender.",
      "Stir in lime juice and chopped cilantro.",
      "Season with salt and serve hot.",
    ],
    equipment: ["pot", "measuring cups", "knife", "cutting board", "wooden spoon"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Thai Green Curry",
    cuisine: "Thai",
    skill: "intermediate",
    dietary: ["gluten-free"],
    cookingTime: 30,
    ingredients: [
      { name: "coconut milk", amount: 1.5, unit: "cans" },
      { name: "Thai green curry paste", amount: 3, unit: "tablespoons" },
      { name: "chicken breast", amount: 1.5, unit: "pounds" },
      { name: "Thai basil", amount: 0.5, unit: "cup" },
      { name: "Thai chilies", amount: 2, unit: "" },
      { name: "lime juice", amount: 2, unit: "tablespoons" },
      { name: "fish sauce", amount: 1, unit: "tablespoon" },
      { name: "palm sugar", amount: 1, unit: "teaspoon" },
    ],
    steps: [
      "Cut chicken into bite-sized pieces.",
      "Heat coconut milk in a large pot over medium heat.",
      "Stir in curry paste and simmer for 2-3 minutes.",
      "Add chicken pieces and simmer until cooked through, about 10-15 minutes.",
      "Add lime juice, fish sauce, and palm sugar.",
      "Add Thai basil and fresh chilies just before serving.",
      "Serve over jasmine rice.",
    ],
    equipment: ["pot", "knife", "cutting board", "measuring spoons", "spoon"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Margherita Pizza",
    cuisine: "Italian",
    skill: "intermediate",
    dietary: ["vegetarian"],
    cookingTime: 20,
    ingredients: [
      { name: "pizza dough", amount: 1, unit: "pound" },
      { name: "tomato sauce", amount: 0.75, unit: "cup" },
      { name: "fresh mozzarella", amount: 0.5, unit: "pound" },
      { name: "fresh basil", amount: 0.25, unit: "cup" },
      { name: "olive oil", amount: 2, unit: "tablespoons" },
      { name: "salt", amount: 0.5, unit: "teaspoon" },
      { name: "black pepper", amount: 0.25, unit: "teaspoon" },
    ],
    steps: [
      "Preheat oven to 475°F.",
      "Stretch pizza dough and place on a pizza pan.",
      "Spread tomato sauce evenly over the dough.",
      "Tear fresh mozzarella and distribute over the sauce.",
      "Drizzle with olive oil and season with salt and pepper.",
      "Bake for 12-15 minutes until crust is golden.",
      "Top with fresh basil and serve immediately.",
    ],
    equipment: ["oven", "pizza pan", "spoon", "knife"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Chicken Stir-Fry",
    cuisine: "Chinese",
    skill: "beginner",
    dietary: ["gluten-free"],
    cookingTime: 15,
    ingredients: [
      { name: "chicken breast", amount: 1.5, unit: "pounds" },
      { name: "soy sauce", amount: 0.33333, unit: "cup" },
      { name: "garlic cloves", amount: 3, unit: "" },
      { name: "ginger", amount: 1, unit: "tablespoon" },
      { name: "vegetable oil", amount: 2, unit: "tablespoons" },
      { name: "bell peppers", amount: 2, unit: "" },
      { name: "broccoli", amount: 2, unit: "cups" },
      { name: "sesame oil", amount: 1, unit: "teaspoon" },
    ],
    steps: [
      "Cut chicken into bite-sized pieces.",
      "Heat oil in a wok or large skillet over high heat.",
      "Add minced garlic and ginger, cook for 30 seconds.",
      "Add chicken and cook until no longer pink.",
      "Add bell peppers and broccoli, stir-fry for 3-4 minutes.",
      "Add soy sauce and sesame oil.",
      "Toss everything together and serve hot over rice.",
    ],
    equipment: ["wok or large skillet", "knife", "cutting board", "spatula"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Greek Salad",
    cuisine: "Mediterranean",
    skill: "beginner",
    dietary: ["vegetarian", "gluten-free"],
    cookingTime: 10,
    ingredients: [
      { name: "tomatoes", amount: 4, unit: "" },
      { name: "cucumber", amount: 1, unit: "" },
      { name: "red onion", amount: 0.5, unit: "" },
      { name: "Kalamata olives", amount: 1, unit: "cup" },
      { name: "feta cheese", amount: 0.5, unit: "cup" },
      { name: "olive oil", amount: 0.25, unit: "cup" },
      { name: "lemon juice", amount: 2, unit: "tablespoons" },
      { name: "oregano", amount: 1, unit: "teaspoon" },
    ],
    steps: [
      "Chop tomatoes into chunks.",
      "Dice cucumber and thinly slice red onion.",
      "Combine tomatoes, cucumber, onion, and olives in a large bowl.",
      "Crumble feta cheese over the vegetables.",
      "In a small bowl, whisk together olive oil, lemon juice, and oregano.",
      "Pour dressing over salad and toss gently.",
      "Serve immediately.",
    ],
    equipment: ["knife", "cutting board", "large bowl", "small bowl", "whisk"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Beef Tacos",
    cuisine: "Mexican",
    skill: "beginner",
    dietary: [],
    cookingTime: 20,
    ingredients: [
      { name: "ground beef", amount: 1.5, unit: "pounds" },
      { name: "taco seasoning", amount: 2, unit: "tablespoons" },
      { name: "taco shells", amount: 12, unit: "" },
      { name: "shredded cheese", amount: 1, unit: "cup" },
      { name: "lettuce", amount: 2, unit: "cups" },
      { name: "tomatoes", amount: 2, unit: "" },
      { name: "sour cream", amount: 0.5, unit: "cup" },
      { name: "salsa", amount: 0.75, unit: "cup" },
    ],
    steps: [
      "Brown ground beef in a large skillet over medium-high heat.",
      "Drain excess fat from the beef.",
      "Add taco seasoning and water according to package directions.",
      "Simmer for 2-3 minutes.",
      "Warm taco shells according to package directions.",
      "Chop lettuce and dice tomatoes.",
      "Fill taco shells with seasoned beef.",
      "Top with cheese, lettuce, tomatoes, sour cream, and salsa.",
    ],
    equipment: ["skillet", "spoon", "knife", "cutting board"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Pad Thai",
    cuisine: "Thai",
    skill: "intermediate",
    dietary: ["gluten-free"],
    cookingTime: 20,
    ingredients: [
      { name: "rice noodles", amount: 0.5, unit: "pound" },
      { name: "shrimp", amount: 1, unit: "pound" },
      { name: "Pad Thai sauce", amount: 0.5, unit: "cup" },
      { name: "eggs", amount: 2, unit: "" },
      { name: "garlic cloves", amount: 3, unit: "" },
      { name: "peanuts", amount: 0.33333, unit: "cup" },
      { name: "lime", amount: 1, unit: "" },
      { name: "green onions", amount: 2, unit: "" },
    ],
    steps: [
      "Soak rice noodles in warm water for 30 minutes.",
      "Heat oil in a wok over high heat.",
      "Add minced garlic and cook for 30 seconds.",
      "Add shrimp and cook until pink.",
      "Push shrimp to the side and add beaten eggs, scrambling lightly.",
      "Add drained noodles and Pad Thai sauce.",
      "Toss everything together for 2-3 minutes.",
      "Top with crushed peanuts, lime wedge, and green onions.",
    ],
    equipment: ["wok", "knife", "cutting board", "spatula", "bowl"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Falafel Wrap",
    cuisine: "Mediterranean",
    skill: "beginner",
    dietary: ["vegan", "vegetarian"],
    cookingTime: 25,
    ingredients: [
      { name: "canned chickpeas", amount: 2, unit: "cans" },
      { name: "onion", amount: 0.5, unit: "" },
      { name: "garlic cloves", amount: 3, unit: "" },
      { name: "fresh parsley", amount: 0.5, unit: "cup" },
      { name: "flour", amount: 0.33333, unit: "cup" },
      { name: "cumin", amount: 1.5, unit: "teaspoons" },
      { name: "baking powder", amount: 0.5, unit: "teaspoon" },
      { name: "olive oil", amount: 3, unit: "tablespoons" },
    ],
    steps: [
      "Drain and rinse chickpeas.",
      "Pulse chickpeas, onion, garlic, and parsley in a food processor.",
      "Add flour, cumin, and baking powder, pulse until combined.",
      "Form mixture into small balls.",
      "Heat olive oil in a skillet over medium-high heat.",
      "Fry falafel until golden brown on all sides.",
      "Serve in warm pita wraps with tahini sauce and vegetables.",
    ],
    equipment: ["food processor", "skillet", "spoon", "knife"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Chicken Curry",
    cuisine: "Indian",
    skill: "intermediate",
    dietary: ["gluten-free"],
    cookingTime: 40,
    ingredients: [
      { name: "chicken breast", amount: 2, unit: "pounds" },
      { name: "coconut milk", amount: 1, unit: "can" },
      { name: "onion", amount: 1.5, unit: "" },
      { name: "garlic cloves", amount: 4, unit: "" },
      { name: "ginger", amount: 1, unit: "tablespoon" },
      { name: "curry powder", amount: 2, unit: "tablespoons" },
      { name: "tomato paste", amount: 2, unit: "tablespoons" },
      { name: "ghee", amount: 3, unit: "tablespoons" },
    ],
    steps: [
      "Heat ghee in a large pot over medium heat.",
      "Sauté diced onion, garlic, and ginger until fragrant.",
      "Add curry powder and tomato paste, cook for 1-2 minutes.",
      "Cut chicken into cubes and add to the pot.",
      "Cook chicken until browned on all sides.",
      "Add coconut milk and bring to a simmer.",
      "Simmer for 20-25 minutes until chicken is cooked through.",
      "Serve over basmati rice.",
    ],
    equipment: ["pot", "knife", "cutting board", "spoon"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Caesar Salad",
    cuisine: "American",
    skill: "beginner",
    dietary: ["vegetarian"],
    cookingTime: 15,
    ingredients: [
      { name: "romaine lettuce", amount: 1, unit: "head" },
      { name: "Parmesan cheese", amount: 0.5, unit: "cup" },
      { name: "croutons", amount: 1.5, unit: "cups" },
      { name: "Caesar dressing", amount: 0.75, unit: "cup" },
      { name: "lemon juice", amount: 1, unit: "tablespoon" },
      { name: "black pepper", amount: 0.25, unit: "teaspoon" },
      { name: "salt", amount: 0.25, unit: "teaspoon" },
    ],
    steps: [
      "Wash and chop romaine lettuce into bite-sized pieces.",
      "Place lettuce in a large bowl.",
      "Add croutons and grated Parmesan cheese.",
      "Drizzle Caesar dressing over the salad.",
      "Toss gently until all ingredients are coated.",
      "Squeeze fresh lemon juice over the top.",
      "Season with salt and pepper, serve immediately.",
    ],
    equipment: ["cutting board", "knife", "large bowl"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Salmon Fillet",
    cuisine: "American",
    skill: "beginner",
    dietary: ["gluten-free", "paleo"],
    cookingTime: 20,
    ingredients: [
      { name: "salmon fillet", amount: 1.5, unit: "pounds" },
      { name: "olive oil", amount: 2, unit: "tablespoons" },
      { name: "lemon", amount: 1, unit: "" },
      { name: "garlic cloves", amount: 2, unit: "" },
      { name: "fresh herbs", amount: 2, unit: "tablespoons" },
      { name: "salt", amount: 0.5, unit: "teaspoon" },
      { name: "black pepper", amount: 0.25, unit: "teaspoon" },
    ],
    steps: [
      "Preheat oven to 400°F.",
      "Place salmon skin-side down on a baking sheet.",
      "Drizzle with olive oil and season with salt and pepper.",
      "Top with minced garlic and fresh herbs.",
      "Squeeze lemon juice over the salmon.",
      "Bake for 12-15 minutes until cooked through.",
      "Serve with lemon wedges and roasted vegetables.",
    ],
    equipment: ["oven", "baking sheet", "knife", "measuring spoons"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Shakshuka",
    cuisine: "Middle Eastern",
    skill: "intermediate",
    dietary: ["vegetarian", "gluten-free"],
    cookingTime: 25,
    ingredients: [
      { name: "canned tomatoes", amount: 1, unit: "can" },
      { name: "onion", amount: 1, unit: "" },
      { name: "bell pepper", amount: 1, unit: "" },
      { name: "garlic cloves", amount: 3, unit: "" },
      { name: "eggs", amount: 6, unit: "" },
      { name: "cumin", amount: 1, unit: "teaspoon" },
      { name: "paprika", amount: 0.5, unit: "teaspoon" },
      { name: "olive oil", amount: 3, unit: "tablespoons" },
    ],
    steps: [
      "Heat olive oil in a large skillet over medium heat.",
      "Sauté diced onion, bell pepper, and garlic.",
      "Add cumin and paprika, cook for 1 minute.",
      "Add canned tomatoes and simmer for 10 minutes.",
      "Make 6 small wells in the sauce.",
      "Crack an egg into each well.",
      "Cover and simmer until eggs are cooked to desired doneness.",
      "Serve with warm pita bread.",
    ],
    equipment: ["skillet", "knife", "cutting board", "spoon"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Vegetable Stir-Fry",
    cuisine: "Chinese",
    skill: "beginner",
    dietary: ["vegan", "vegetarian", "gluten-free"],
    cookingTime: 15,
    ingredients: [
      { name: "broccoli", amount: 3, unit: "cups" },
      { name: "carrots", amount: 2, unit: "" },
      { name: "snap peas", amount: 2, unit: "cups" },
      { name: "garlic cloves", amount: 3, unit: "" },
      { name: "ginger", amount: 1, unit: "tablespoon" },
      { name: "soy sauce", amount: 3, unit: "tablespoons" },
      { name: "vegetable oil", amount: 2, unit: "tablespoons" },
      { name: "sesame oil", amount: 1, unit: "teaspoon" },
    ],
    steps: [
      "Cut all vegetables into uniform sizes.",
      "Heat oil in a wok over high heat.",
      "Add garlic and ginger, cook for 30 seconds.",
      "Add harder vegetables first (carrots and broccoli).",
      "Stir-fry for 2-3 minutes.",
      "Add snap peas and continue cooking.",
      "Add soy sauce and sesame oil.",
      "Toss everything together and serve over rice.",
    ],
    equipment: ["wok", "knife", "cutting board", "spatula"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Omelette",
    cuisine: "French",
    skill: "beginner",
    dietary: ["vegetarian", "gluten-free"],
    cookingTime: 10,
    ingredients: [
      { name: "eggs", amount: 3, unit: "" },
      { name: "butter", amount: 1, unit: "tablespoon" },
      { name: "cheese", amount: 0.25, unit: "cup" },
      { name: "bell pepper", amount: 0.5, unit: "" },
      { name: "onion", amount: 0.25, unit: "" },
      { name: "salt", amount: 0.25, unit: "teaspoon" },
      { name: "black pepper", amount: 0.125, unit: "teaspoon" },
    ],
    steps: [
      "Beat eggs in a bowl with salt and pepper.",
      "Melt butter in a non-stick skillet over medium-high heat.",
      "Pour beaten eggs into the skillet.",
      "Let eggs set slightly, then gently push cooked portions to the center.",
      "Add diced vegetables and cheese to one half.",
      "Fold omelette in half when mostly cooked.",
      "Slide onto a plate and serve immediately.",
    ],
    equipment: ["skillet", "bowl", "whisk", "spatula", "knife"],
    source: "seeded",
    status: "approved",
  },
  {
    title: "Risotto Milanese",
    cuisine: "Italian",
    skill: "intermediate",
    dietary: ["vegetarian", "gluten-free"],
    cookingTime: 30,
    ingredients: [
      { name: "arborio rice", amount: 1.5, unit: "cups" },
      { name: "vegetable broth", amount: 5, unit: "cups" },
      { name: "white wine", amount: 0.5, unit: "cup" },
      { name: "onion", amount: 0.5, unit: "" },
      { name: "garlic cloves", amount: 2, unit: "" },
      { name: "saffron threads", amount: 0.125, unit: "teaspoon" },
      { name: "butter", amount: 2, unit: "tablespoons" },
      { name: "Parmesan cheese", amount: 0.5, unit: "cup" },
    ],
    steps: [
      "Heat broth in a separate pot and keep warm.",
      "Melt butter in a large pot and sauté diced onion and garlic.",
      "Add arborio rice and toast for 1-2 minutes.",
      "Pour in white wine and stir until absorbed.",
      "Add warm broth one ladle at a time, stirring frequently.",
      "Continue adding broth until rice is creamy and cooked through.",
      "Stir in saffron threads and Parmesan cheese.",
      "Serve immediately.",
    ],
    equipment: ["pot", "wooden spoon", "knife", "cutting board"],
    source: "seeded",
    status: "approved",
  },
];

export async function POST(req: Request) {
  try {
    // Check for admin API key
    const apiKey = req.headers.get("x-api-key");
    if (apiKey !== process.env.ADMIN_API_KEY) {
      return Response.json({ error: "Unauthorized" }, { status: 401 });
    }

    const client = await clientPromise;
    const db = client.db();
    const recipesCollection = db.collection("recipes");

    // Delete existing seeded recipes
    const deleteResult = await recipesCollection.deleteMany({ source: "seeded" });

    // Insert new seeded recipes
    const insertResult = await recipesCollection.insertMany(
      SEEDED_RECIPES.map((recipe) => ({
        ...recipe,
        createdAt: new Date(),
        updatedAt: new Date(),
      }))
    );

    return Response.json({
      message: "Seeded recipes added successfully",
      deletedCount: deleteResult.deletedCount,
      insertedCount: insertResult.insertedCount,
    });
  } catch (error) {
    console.error("Seeding error:", error);
    return Response.json({ error: "Seeding failed" }, { status: 500 });
  }
}
